### ISSUE TITLE
Feature request: sound notification

### ISSUE THREAD

**Issue by juandiegoabijah** [flytaly/reddit-post-notifier#1]
Hey man, thank you very much for the addon, I like it very much. Would it be possible to add a sound notification? maybe with a toggle or something, your app is really fast when showing the notifications, but sometimes I'm not looking and I need to hear it in order to open the latest post

thanks in advance!

**Comment by flytaly** [comment]
Hello. 
There should be system notification sound but it seems it doesn't work on Windows for some reasons. 
I added support for [Notification Sound](https://addons.mozilla.org/en-US/firefox/addon/notification-sound/) addon. Try to install it, it should help.

**Comment by juandiegoabijah** [comment]
ok I tested it by receiving a PM, which opens like a popup on the right bottom corner of the browser, and in that case it did sound!
but it's not making any sound when a new post is made on one of the configured subreddits, which is the feature I'm interested in

**Comment by juandiegoabijah** [comment]
![imagen](https://user-images.githubusercontent.com/54917627/65182768-080f0c00-da30-11e9-92e3-3ac75789f464.png)
this popup is the one I'm talking about

**Comment by flytaly** [comment]
Did you select this option
![image](https://user-images.githubusercontent.com/1577569/65183306-e3388a00-da6b-11e9-88eb-6c4912e1c00b.png)
?

**Comment by juandiegoabijah** [comment]
ohh that's the issue then!! I just ticked it and now it sounds, thanks man, you're the best! :D I love your plugin
