### ISSUE TITLE
Link to old reddit

### ISSUE THREAD

**Issue by magnulen** [flytaly/reddit-post-notifier#12]
Hello. 

Could it be possible to add an option for the notifications to link to the old.reddit version of the site? :)

**Comment by flytaly** [comment]
Yes, I've added this option in version 3.2.0:

![Screenshot 2020-12-29 at 18 08 21](https://user-images.githubusercontent.com/1577569/103293371-d8a3c900-4a00-11eb-9643-85a096983c39.png)

It's already available in Firefox and will be available after review in the Chrome Store.
