### ISSUE TITLE
Opens up 2 duplicate tabs

### ISSUE THREAD

**Issue by kaisei15** [flytaly/reddit-post-notifier#14]
When I click the button to "open subreddit or search in new browser tab" it opens 2 identical tabs. Not sure why it just suddenly started happening after an hour or two of installing the add-on. Tried restarting firefox but that did not help.

**Comment by flytaly** [comment]
Should be fixed now in v.3.3.1.

Chrome by default doesn't open links in the extension's popup so it should be forced to open a new tab.  Meanwhile, Firefox works as you would expect. That's where double opening comes from: extension opens one tab and then Firefox opens another one.

Apparently, [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) prevent double opening and that was why it worked correctly for me.

**Comment by kaisei15** [comment]
Just updated and tested. Seems to be working as expected now. Thanks!
