### ISSUE TITLE
Multi-user support

### ISSUE THREAD

**Issue by bagarwa** [flytaly/reddit-post-notifier#17]
Right now this extension supports only one user. Will it be possible to support multiple users; so that I can get notified for new messages for all of them?

As in, I'll add multiple users at Mail > authorization section and enable "Unread mail" checkbox for all of them. Whenever any of them receives a new mail, I will get a notification and clicking that notification will open that new msg, switching my user in reddit if necessary.

**Comment by flytaly** [comment]
I've added it in v4. It is also possible to view unread messages in the toolbar popup.
