### ISSUE TITLE
Suggestion: Exclude some authors

### ISSUE THREAD

**Issue by abi-21** [flytaly/reddit-post-notifier#21]
I apologise if this was already implemented, but is it possible to filter out certain users who posts often because I'm not interested in their content, so I can tone down the spam in notification?

**Comment by flytaly** [comment]
In subreddit filters? No, it's not possible. I didn't implement negative filters.

But you can use Reddit Search with query `NOT author:`.

For example, follow posts in r/changelog that wasn't submitted by BusyV: NOT author:BusyV
 
![reddit search](https://user-images.githubusercontent.com/1577569/149658817-4a70ba43-c90b-4311-b6de-1d5dea121f1b.png)

vs follow every posts

![all posts](https://user-images.githubusercontent.com/1577569/149658946-2eaf8bfc-c198-434e-9a28-81f34904f6de.png)

**Comment by abi-21** [comment]
Thank you for the quick response, but I was only interested in filtering out notifications from extension because I already use Reddit Enhancement Suite to ignore the users on subreddits. If it's not possible like you said, I'll close this issue. 
Great extension btw, helps me a lot 👍
