### ISSUE TITLE
Accounts authorization expires after few days

### ISSUE THREAD

**Issue by bagarwa** [flytaly/reddit-post-notifier#22]
I am using 3 reddit accounts and had saved their login auth in this extension's "Messages and Accounts" section and enabled "watch for messages" toggle. It works for few days. And then it loses the authorization, telling me to reauthorize the accounts. Having to do this for 3 accounts every few days is very irritating. Please look into it. 

![Reddit](https://user-images.githubusercontent.com/4424058/152706147-f52f3235-b991-456e-92bf-5dd7cd44c61e.jpg)

**Comment by flytaly** [comment]
I will look into it. 

All errors with code >500 are server side errors. In other words, Reddit API was down during access token updating. But extension "thought" that token was rejected by Reddit and disabled future updating.

Considering that there was another issue with Reddit messages today https://github.com/flytaly/reddit-post-notifier/issues/23, it seems that Reddit message API works poorly lately.

I can't fix the errors themselves, but I can update the extension, so it will wait until Reddit works again.

**Comment by flytaly** [comment]
Version 4.1.1 is available. The issue should be fixed, if not then reopen it.
