### ISSUE TITLE
Is there a way to Export/Import all searches and filters

### ISSUE THREAD

**Issue by Akshat-h** [flytaly/reddit-post-notifier#26]
I have setup lots of filters and followed users. And i want to copy those filters on a different computer.
I cant access my current mail id on new machine. 
And setting up everything manually will take a lot of time.
So I wanted to know if there is a way to Export all settings and filters/searches to a file 
and restore them back on a new machine. 

Im using Google Chrome stable latest version on a windows 10 machine.

**Comment by flytaly** [comment]
Version 4.2.0 with `Backup` page is available in the Chrome store.
