### ISSUE TITLE
Please could you add to set names to custom filters just like we can name our searches?

### ISSUE THREAD

**Issue by Joanxt** [flytaly/reddit-post-notifier#30]
As title says, dunno if this is something that you have in mind or if it can be done, but i'd appreciate a way to set names to filters when monitoring subreddits.

Thanks again, your extension is super useful.

**Comment by flytaly** [comment]
Display name input was adden in V5.

![image](https://user-images.githubusercontent.com/1577569/198824410-39cd4ca9-7f20-4774-b07f-03acde6c1e97.png)
