### ISSUE TITLE
Notification on Edge Browser

### ISSUE THREAD

**Issue by tiznerts** [flytaly/reddit-post-notifier#31]
For some reason, since friday I have not seen notifications of some subreddits. I am not talking about the notification sound or anything. Talking about the notifications that appear on the extension panel

**Comment by flytaly** [comment]
Do you mean that there are no messages in the extension popup?

Like this

![popup](https://user-images.githubusercontent.com/1577569/172642114-967ce4f2-221e-4610-8ab2-59d9b556a6c8.png)

or you don't have desktop notifications like this

![notification](https://user-images.githubusercontent.com/1577569/172642265-d9018553-02ca-4d4d-b9b2-538a77344da0.png)
?

**Comment by tiznerts** [comment]
Found out what was wrong,one of the subreddit that was on the extension got
banned so it blocked the notifications for the other subreddit i had on the
extension

**Comment by flytaly** [comment]
Wow, nice find. It really is a bug in the extension. An error in one of the subreddits shouldn't stop updates of the others.

**Comment by tiznerts** [comment]
Noted something else, don't know if it is the subreddit but the
notifications come after a few hours or days

**Comment by tiznerts** [comment]
Yes, thanks for your time
