### ISSUE TITLE
Integrate troddit to open links

### ISSUE THREAD

**Issue by dtantono** [flytaly/reddit-post-notifier#33]
Hi
I know we can Use old reddit to open links. Can we integrate with troddit?
https://github.com/burhan-syed/troddit

**Comment by flytaly** [comment]
Open link troddit.com? Yes, it is possible. I plan to update the extension this month and will probably add this.

**Comment by flytaly** [comment]
In version 5 you can now change base address

![image](https://user-images.githubusercontent.com/1577569/198824285-8de9c77c-edcb-4f52-b1c7-aa37fc0fbd17.png)
