### ISSUE TITLE
Integrate Reddit Sharp to open links 

### ISSUE THREAD

**Issue by dtantono** [flytaly/reddit-post-notifier#34]
Hi
I know we can Use old reddit to open links. Can we integrate with Reddit Sharp?
https://github.com/grey-codes/RedditSharp

**Comment by flytaly** [comment]
Open link troddit.com? Yes, it is possible. I plan to update the extension this month and will probably add this.

**Comment by flytaly** [comment]
https://github.com/flytaly/reddit-post-notifier/issues/33#issuecomment-1295784364
