### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by siffegh** [flytaly/reddit-post-notifier#36]
Please add an opt-in choice to open the inbox directly.

**Comment by flytaly** [comment]
I'm not sure if I understand. It is already possible to open the inbox in two ways:

![image](https://user-images.githubusercontent.com/1577569/199782897-d76cde9a-dad9-414e-9eb2-be0d931e70f4.png)

**Comment by siffegh** [comment]
What I mean is this - only one click to open the inbox.

![image](https://user-images.githubusercontent.com/18728013/199853459-a3b1d596-f260-43bc-8143-9fc6c5852ae8.png)

**Comment by siffegh** [comment]
Thanks a lot, @flytaly!
