### ISSUE TITLE
Display name not respected in notification dialog

### ISSUE THREAD

**Issue by shanet** [flytaly/reddit-post-notifier#38]
I have a display name set for subreddit alerts.

Expected behavior: In the notification dialog for an alert I'd expect the display name to be used there.

Actual behavior: The subreddit name is always used and the display name is seemingly ignored.

Browser: Firefox 109 (Nightly build)
Extension version: 5.1.0

Great extension, by the way! It works wonderfully.

**Comment by flytaly** [comment]
Oops, forgot to update the text in the notification.
Fixed in latest version.
