### ISSUE TITLE
Will reddit-post-notifier be affected by the upcoming changes regarding Reddit's API?

### ISSUE THREAD

**Issue by appel** [flytaly/reddit-post-notifier#42]
Sorry if this was mentioned already elsewhere. Will reddit-post-notifier be affected by the upcoming changes regarding Reddit's API on July 1st 2023?

**Comment by flytaly** [comment]
Yes. If I have time, I will try to update the extension before July.

It looks like the extension will no longer support OAuth, which means that checking personal email from multiple accounts will not be possible.

Also, under the [new rules](https://support.reddithelp.com/hc/en-us/articles/16160319875092-Reddit-Data-API-Wiki), there will be a limit of 10 requests per minute.

There is another problem. Google is moving extensions to Manifest V3, which limits the lifetime of background extension scripts and only allows "alarms" to trigger updates, with one alarm per minute at most. 

So, by default, the extension will check Reddit once a minute with no more than 10 requests (subreddits or multireddits).

**Comment by appel** [comment]
Sounds like a perfect solution to imperfect circumstances. Thanks, @flytaly, much appreciated.
