### ISSUE TITLE
Fetch error: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by cramberries** [flytaly/reddit-post-notifier#45]
Hi, not sure if this extension is still being supported but on the off-chance that it is, I would like to report this issue.

I first noticed it a few days ago but not sure when it started exactly. I saw a similar thread here that said it's a Reddit issue and that after they waited a day or so, it fixed itself so that's what I did. But that didn't seem to work this time or perhaps I needed to wait a little longer?

Either way, I just thought of reporting it here just in case. Thank you.

Windows 10 64-bit
Firefox 120.0.1
Reddit Post Notifier v. 5.1.1

**Comment by flytaly** [comment]
> v.5.1.1

There is a newer version 6, but I didn't upload it to Firefox because it didn't fully support Manifest V3 at the time. I will try to update it then.



About the issue. Can you see JSON endpoints in your browser? Just add .json at then end. For example, if you watch for new posts in `r/pics`, JSON path would be https://www.reddit.com/r/pics/new.json
The extension uses them to fetch new posts. The result should start with something like `{"kind": "Listing", "data":`

If they work, then try to log out (if you are logged in) from your account and fetch again 

![image](https://github.com/flytaly/reddit-post-notifier/assets/1577569/2fd31607-51fc-43ce-88dd-bbc1d6de2c4e)

Also try to check posts once with fetch posts button

![image](https://github.com/flytaly/reddit-post-notifier/assets/1577569/2bdcb4a1-55f7-4d8a-94cd-ebd0cc06992a)

**Comment by cramberries** [comment]
@flytaly
Hello. Thank you for the quick response!

>Can you see JSON endpoints in your browser?

Yes, I can view a JSON "link" in the browser. And after switching to the Raw Data tab, it does show `{"kind": "Listing", "data": ...` in the first line.

>If they work, then try to log out (if you are logged in) from your account and fetch again

I don't have any authorised accounts since I primarily use the extension just to check new posts in certain subreddits but I've tried the fetch buttons as well as the update button on the toolbar dropdown, the error icons still persist.

> Also try to check posts once with fetch posts button

Just the "No items" text box shows up after pressing the "fetch posts" button:

![image](https://github.com/flytaly/reddit-post-notifier/assets/101653843/6bcae3c0-7b60-4eb7-8dfb-7918ae9a1849)

**Comment by flytaly** [comment]
The latest version is now available in Firefox. Is this still happening after the update?

**Comment by cramberries** [comment]
@flytaly
Wow, thank you for the quick update!

For some reason, it wouldn't auto-update and I had to reinstall the extension again. After I did and set it up similar to my previous installation, it's now giving back a 403 error whenever I try to fetch posts. Not sure what's causing it but I did allow it permission to access reddit.com.

**Comment by flytaly** [comment]
403 error can happen when you try to access private subreddits like r/lounge or r/CenturyClub. 

![image](https://github.com/flytaly/reddit-post-notifier/assets/1577569/3045e340-a651-4445-b427-4b4faa17ae89)

**Comment by cramberries** [comment]
@flytaly
I only have open subreddits on the list and every single one returns a 403.

But I tried playing around and figured what's causing it, my VPN connection. So, I guess this is an isolated case and I will be closing this thread. I'm sorry for the bother. 😅 

But if you don't mind me asking, do you have any idea why the extension suddenly stopped working with a VPN connection? I'm using a VPN with proper software and not just a browser extension if that matters. I never had this problem with Reddit Post Notifier before and everything else in the browser still works as intended.

**Comment by flytaly** [comment]
Your VPN is probably banned or/and ratelimited.  There was relevant discussion recently about RSS feeds (you can access them the same way as JSON [r/aww/new.rss](https://www.reddit.com/r/aww/new.rss))

[403 when accessing RSS feeds](https://www.reddit.com/r/redditdev/comments/18iuk10/403_when_accessing_rss_feeds)

In the new version (v6) of the extension, the settings page in the bottom left corner shows ratelimits (only works during updates).

![image](https://github.com/flytaly/reddit-post-notifier/assets/1577569/264bc62d-9f90-44e9-898b-8d9fb0b6633f)
