### ISSUE TITLE
Disable Trending notifications

### ISSUE THREAD

**Issue by tito356** [flytaly/reddit-post-notifier#8]
Is it possible to disable notifications for what subreddit is trending?

**Comment by flytaly** [comment]
This is unrelated to the extension. Reddit itself sends them. 
I suppose you can disable them on this page in settings: [new.reddit.com/settings/notifications](https://new.reddit.com/settings/notifications)
![Screenshot 2020-11-18 at 01 51 37](https://user-images.githubusercontent.com/1577569/99460265-9aff4b00-2940-11eb-9020-086eefd31abf.png)
.

**Comment by tito356** [comment]
I already have this off. I started receiving trending notifications once I installed the extension.

**Comment by flytaly** [comment]
It's strange, maybe just coincidence. This extension has 3 notification types:
new mail
![Screenshot 2020-11-18 at 17 16 05](https://user-images.githubusercontent.com/1577569/99541324-c0806900-29c1-11eb-865d-9980113fbd18.png)

new post in subreddit
![Screenshot 2020-11-18 at 17 15 21](https://user-images.githubusercontent.com/1577569/99541256-a5adf480-29c1-11eb-9dd9-c5cf87b01cba.png)

new post in reddit search
![Screenshot 2020-11-18 at 17 15 46](https://user-images.githubusercontent.com/1577569/99541302-b52d3d80-29c1-11eb-9b60-f4485b03bf76.png)

And notifications that this extension creates should have the extension's icon:
![notification](https://user-images.githubusercontent.com/54917627/65182768-080f0c00-da30-11e9-92e3-3ac75789f464.png)

Do you have this icon? If not then it's definitely not from my extension.

Btw if change settings won't help maybe disable browser notification for this site altogether in the browser's settings.
