### ISSUE TITLE
Boolean operators search

### ISSUE THREAD

**Issue by Duos-Apros** [flytaly/reddit-post-notifier#9]
Thanks for this add-on.  For the "Watch for specific posts in the subreddit", is the add-on designed to handle Boolean operators? For example, using the reddit search wiki (https://www.reddit.com/wiki/search), I put the following settings:

Watch for specific posts in the subreddit:
Name: ABC
Subreddit: XYZ
Search query: title: "keyword 1" OR "keyword 2" OR "keyword 3" OR "keyword 4" OR "keyword 5"

The problem is that the search results from the add-on show post titles that are not related to any of the keywords. Am I doing something wrong?

**Comment by flytaly** [comment]
This should work if you remove spaces between title: and "keyword ..." and repeat title (if needed) every time

Search query: `title:"keyword 1" OR title:"keyword 2"`

**Comment by Duos-Apros** [comment]
Worked like charm.  Spasibo!
